// ============================================================
// SMARTNOTE — PDF Export Utility (client-side)
// ============================================================

import jsPDF from 'jspdf';

export async function exportElementToPDF(
  elementId: string,
  filename: string = 'smartnote-export.pdf'
) {
  const element = document.getElementById(elementId);
  if (!element) throw new Error('Element not found');

  const html2canvas = (await import('html2canvas')).default;
  const canvas = await html2canvas(element, {
    backgroundColor: '#0a0a0a',
    scale: 2,
    useCORS: true,
    logging: false,
  });

  const imgData = canvas.toDataURL('image/png');
  const pdf = new jsPDF({
    orientation: canvas.width > canvas.height ? 'landscape' : 'portrait',
    unit: 'px',
    format: [canvas.width, canvas.height],
  });

  pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
  pdf.save(filename);
}

export function exportTextToPDF(
  title: string,
  sections: { heading: string; content: string }[],
  filename: string = 'smartnote-export.pdf'
) {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  // Title
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, margin, y);
  y += 12;

  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(128);
  pdf.text(`Generated by SMARTNOTE — ${new Date().toLocaleDateString()}`, margin, y);
  pdf.setTextColor(0);
  y += 10;

  // Divider
  pdf.setDrawColor(200);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 8;

  for (const section of sections) {
    // Check if we need a new page
    if (y > pdf.internal.pageSize.getHeight() - 30) {
      pdf.addPage();
      y = margin;
    }

    // Section heading
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    const headLines = pdf.splitTextToSize(section.heading, maxWidth);
    pdf.text(headLines, margin, y);
    y += headLines.length * 7 + 3;

    // Section content
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    const contentLines = pdf.splitTextToSize(section.content, maxWidth);

    for (const line of contentLines) {
      if (y > pdf.internal.pageSize.getHeight() - 20) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(line, margin, y);
      y += 5;
    }
    y += 6;
  }

  pdf.save(filename);
}

export function exportFlashcardsToPDF(
  cards: { front: string; back: string; difficulty: string }[],
  filename: string = 'smartnote-flashcards.pdf'
) {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const margin = 15;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const cardWidth = pageWidth - margin * 2;
  let y = margin;

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text('SMARTNOTE Flashcards', margin, y);
  y += 12;

  for (let i = 0; i < cards.length; i++) {
    if (y > pdf.internal.pageSize.getHeight() - 40) {
      pdf.addPage();
      y = margin;
    }

    const card = cards[i];

    // Card box
    pdf.setDrawColor(180);
    pdf.setFillColor(245, 245, 250);
    pdf.roundedRect(margin, y, cardWidth, 30, 3, 3, 'FD');

    // Q
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`Q${i + 1}: ${card.front}`, margin + 4, y + 8);

    // A
    pdf.setFont('helvetica', 'normal');
    const ansLines = pdf.splitTextToSize(`A: ${card.back}`, cardWidth - 8);
    pdf.text(ansLines, margin + 4, y + 16);

    // Difficulty badge
    pdf.setFontSize(7);
    pdf.text(`[${card.difficulty}]`, margin + cardWidth - 15, y + 8);

    y += 34;
  }

  pdf.save(filename);
}

export function exportQuizToPDF(
  quiz: { title: string; questions: { question: string; options?: string[]; correctAnswer: string; explanation?: string }[] },
  filename: string = 'smartnote-quiz.pdf'
) {
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const margin = 15;
  const maxWidth = pdf.internal.pageSize.getWidth() - margin * 2;
  let y = margin;

  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.text(quiz.title, margin, y);
  y += 12;

  for (let i = 0; i < quiz.questions.length; i++) {
    if (y > pdf.internal.pageSize.getHeight() - 40) {
      pdf.addPage();
      y = margin;
    }

    const q = quiz.questions[i];
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    const qLines = pdf.splitTextToSize(`${i + 1}. ${q.question}`, maxWidth);
    pdf.text(qLines, margin, y);
    y += qLines.length * 5 + 3;

    if (q.options) {
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      for (const opt of q.options) {
        if (y > pdf.internal.pageSize.getHeight() - 15) {
          pdf.addPage();
          y = margin;
        }
        pdf.text(`   ${opt}`, margin, y);
        y += 5;
      }
    }
    y += 4;
  }

  // Answer key on new page
  pdf.addPage();
  y = margin;
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Answer Key', margin, y);
  y += 10;

  for (let i = 0; i < quiz.questions.length; i++) {
    if (y > pdf.internal.pageSize.getHeight() - 20) {
      pdf.addPage();
      y = margin;
    }
    const q = quiz.questions[i];
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${i + 1}. ${q.correctAnswer}`, margin, y);
    y += 5;
    if (q.explanation) {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      const expLines = pdf.splitTextToSize(q.explanation, maxWidth - 5);
      pdf.text(expLines, margin + 5, y);
      y += expLines.length * 4 + 3;
    }
    y += 2;
  }

  pdf.save(filename);
}
